final.mergec <- read.csv("/home/priyanka/Downloads/intern/new_data/csv_files/unigram_gain.csv", header = F, sep = ",")
#head(final.merge)
features_has <- read.csv("/home/priyanka/Downloads/intern/dataset/sentiments_features.csv", header = T, sep = ",")
nrow(features_has)
ncol(final.mergec)
nrow(final.mergec)
head(final.mergec)

final.mergec<-cbind(final.mergec,features_has$at_symbol)
final.mergec<-cbind(final.mergec,features_has$hash_symbol)
final.mergec<-cbind(final.mergec,features_has$adj_count)
final.mergec<-cbind(final.mergec,features_has$adv_count)
final.mergec<-cbind(final.mergec,features_has$happy)
final.mergec<-cbind(final.mergec,features_has$sad)
final.mergec<-cbind(final.mergec,features_has$emotion_sentiment)
final.mergec<-cbind(final.mergec,features_has$happy_word)
final.mergec<-cbind(final.mergec,features_has$neg_word)
final.mergec<-cbind(final.mergec,features_has$words_sentiment)

affin.read<-read.csv("/home/priyanka/Downloads/lexicon-based/AFINN_lexi/out",header = T,sep = ",")
final.mergec<-cbind(final.mergec,affin.read$X0.00)
head(final.mergec)
head(features_has$happy)
write.csv(final.mergec, file ="/home/priyanka/Downloads/intern/new_data/final.csv",row.names=FALSE)
ncol(final.mergec)
